export default{
    notificationsActive:{
        bgcolor:'white',
        width:'397px',
        minHeight:'100vh',
        position: 'fixed',
        top: 0,
        left: '225px',
        zIndex:'2',
        transition:'0.5s',
        boxShadow:'5px 0 10px 0 rgba(0,0,0,0.2)',
    },
    notificationsInActive:{
        bgcolor:'white',
        width:'397px',
        minHeight:'100vh',
        position: 'fixed',
        top: 0,
        left: '-100%',
        zIndex:'0',
        transition:'0.5s',
    },
    notificationsOverlayActive:{
        position:'fixed',
        top:0,
        left:'0',
        width:'100%',
        height:'100%',
        transition:'0.5s',
        opacity:1,
        visibility:'visible',
    },
    notificationsOverlayInActive:{
        position:'fixed',
        top:0,
        left:0,
        width:'100%',
        height:'100%',
        transition:'0.5s',
        opacity:0,
        visibility:'hidden',
    }
}